USE `securevoice`;

-- Seed all Bangladesh districts (idempotent)
INSERT IGNORE INTO districts (district_name) VALUES
('Bagerhat'),
('Bandarban'),
('Barguna'),
('Barishal'),
('Bhola'),
('Bogura'),
('Brahmanbaria'),
('Chandpur'),
('Chapainawabganj'),
('Chattogram'),
('Chuadanga'),
('Cox\'s Bazar'),
('Cumilla'),
('Dhaka'),
('Dinajpur'),
('Faridpur'),
('Feni'),
('Gaibandha'),
('Gazipur'),
('Gopalganj'),
('Habiganj'),
('Jamalpur'),
('Jashore'),
('Jhalokati'),
('Jhenaidah'),
('Joypurhat'),
('Khagrachhari'),
('Khulna'),
('Kishoreganj'),
('Kurigram'),
('Kushtia'),
('Lakshmipur'),
('Lalmonirhat'),
('Madaripur'),
('Magura'),
('Manikganj'),
('Meherpur'),
('Moulvibazar'),
('Munshiganj'),
('Mymensingh'),
('Naogaon'),
('Narail'),
('Narayanganj'),
('Narsingdi'),
('Natore'),
('Netrokona'),
('Nilphamari'),
('Noakhali'),
('Pabna'),
('Panchagarh'),
('Patuakhali'),
('Pirojpur'),
('Rajbari'),
('Rajshahi'),
('Rangamati'),
('Rangpur'),
('Satkhira'),
('Shariatpur'),
('Sherpur'),
('Sirajganj'),
('Sunamganj'),
('Sylhet'),
('Tangail'),
('Thakurgaon');

-- Verify
SELECT district_name FROM districts ORDER BY district_name;
